<?php

$data = [
    'name' => 'Esmail Ali',
    'age' => '24',
    'birth_date' => '24-7-2000',
    'description' => 'A devoted person who adapts to his surroundings. Well-socialized and well-behaved in any environment. Energetic, attentive, and loves to know more.',
    'city' => 'Yemen, Aden',
    'companies' => [
        ['name' => 'DoppleAI',
        'location' => 'Wilmington, DE, USA',
        'from_date' => '05-01-2024',
        'to_date' => '20-03-2024',
        'description_role' => 'Internal Tester',
        'achievements' => ['Discovered a vulnerability that could crash the site', 'Part of the Internal Testers Team, and has tested over 20 chatbots extensively', 'Done researches for a couple of competitors in the field']
        ],
    ],
    'interns' => [
        ['name' => 'Aden Central Bank',
        'from_date' => '20-09-2022',
        'to_date' => '4-10-2022',
        'description_role' => 'Network Trainee',
        'description' => ["Learnt about the status of the network for the bank, the domains and how they're implemented in general"],
        ],
        ['name' => 'BBSoft Academy',
        'from_date' => '24-09-2023',
        'to_date' => '1-10-2023',
        'description_role' => 'C# Desktop Application Developer Trainee',
        'description' => ['Learnt to design a C# Desktop Application with a sign-in window and data-entry window'],
        ]
    ],
    'education' => [
        ['name' => 'University of Aden',
        'from_date' => '26-10-2018',
        'to_date' => '26-11-2024',
        'description_degree' => 'Bachelor of Information Technology and Engineering',
        'degree' => 'Undergraduate',
        'brief_description' => 'Undergraduate in Information Technology Department (IT), An astounding faculty which provides a good workflow and a great community.'
        ],],
    'Skills' => [
        ['name' => 'Ability of dealing with computers',
        'level' => '100',
        'description' => 'handling computers',
        ],
        ['name' => 'Ability of dealing with Microsoft Office',
        'level' => '90',
        'description' => 'ineracting and working with Office suite of applications',
        ],
        ['name' => 'Fast Typing',
        'level' => '90',
        'description' => '',
        ],
        ['name' => 'Ability of dealing and having accurate responses with AI',
        'level' => '90',
        'description' => 'Basics of Prompt Engineering to generate good and accurate responses',
        ],
        ['name' => 'Photoshop & Illustrator & InDesign',
        'level' => '75',
        'description' => 'Basics of Graphic Design, capable of using the tools to build good designs with guidance',
        ],
        ],
    'courses' => [
        ['name' => 'ASP.NET Website Developing',
        'company' => 'BBSoft Academy',
        'from_date' => '12-04-2022',
        'to_date' => '02-03-2023',
        'description' => ['Developing websites using Frontend (HTML,CSS,Bootstrap) and ASP.NET, and MSSQL Server', 'Graduated with a score of 94%'],
        'hours' => '120'
        ],
        ['name' => 'Graphic Design',
        'company' => 'Skills Development Fund',
        'from_date' => '16-07-2024',
        'to_date' => '17-08-2024',
        'description' => ['Learnt to use Adobe Suite Applications (Photoshop, Illustrator, InDesign, AfterEffect)', 'Done a couple of experimental designs as a part of the course completion'],
        'hours' => '80'
        ],
        ['name' => 'Sandbox Business Incubator',
        'company' => "Medalah/SuperNovae/MINISTÈRE DE L'EUROPE ET DES AFFAIRES ÉTRANGÈRES",
        'from_date' => '12-04-2022',
        'to_date' => '02-03-2023',
        'description' => ['Generating sellable ideas, Prototype, Logistics and Distribution','Has done Marketing, Digital Marketing sales, Team, Finance, Strategy and Sustainability, KPIs and Idea Pitching during the course'],
        'hours' => '104'
        ],
    ],
    'technologies_used' => [
        ['name' => 'HTML',
        'level' => '100',
        'description' => 'handling HTML basics',
        ],
        ['name' => 'CSS',
        'level' => '85',
        'description' => 'handling CSS basics',
        ],
        ['name' => 'Bootstrap',
        'level' => '90',
        'description' => 'Handling Bootstrap version 5.0.2',
        ],
        ['name' => 'MSSQL Server',
        'level' => '90',
        'description' => 'handling and using MSSQL Server 2017',
        ],
        ['name' => 'ASP.NET',
        'level' => '80',
        'description' => 'handling ASP.NET Framework as the backend',
        ],
        ['name' => 'C#',
        'level' => '85',
        'description' => 'handling C# as a console programming language',
        ],
    ],
    'languages' => [
        ['name' => 'English',
        'level' => '90',
        'description' => 'Fluent in English',
        ],
        ['name' => 'Arabic',
        'level' => '100',
        'description' => 'Native in Arabic',
        ],
    ],
    'contacts' => [
        ['name' => 'LinkedIn',
         'link' => 'https://www.linkedin.com/in/esmail-ali-42a984324/',
        ],
        ['name' => 'Instagram',
         'link' => 'https://www.instagram.com/esmail6400',
        ],
        ['name' => 'Facebook',
         'link' => 'https://www.facebook.com/profile.php?id=100076865259441',
        ],
        ['name' => 'X',
         'link' => 'https:/www.x.com/itsmrezzy',
        ],
        ['name' => 'Phone Number:',
         'number' => '+967 778 515 331',
        ],
        ['name' => 'Email',
         'email' => 'ez.is.ezzy@gmail.com',
        ],
    ],
];